# configuration for treeClusterSim

simulation:
    startTime: 2020.038161
    totalTime: 0.1643
    timeStep: 0.002738
    seed: clock
    name: snohomish_1

files:
    infectionLinelistFilename: output/snohomish_1/SEIR_COVID_infectionList.csv
    clusterLinelistFilename: output/snohomish_1/SEIR_COVID_clusterList.csv
    incidenceSummaryFilename: output/snohomish_1/SEIR_COVID_incidenceSummary.png        
    timeTreeFilename: output/snohomish_1/SEIR_COVID_phyloTree.tre        
    treeDataFilename: output/snohomish_1/SEIR_COVID_phyloTree_metadata.csv        

clusterModel:
    type: stochasticSEIR
    params:
        latentDuration:
            distribution: positiveNormal
            params:
                mu: 0.011
                sigma: 0.0027
        infectiousDuration:
            distribution: positiveNormal
            params:
                mu: 0.0219
                sigma: 0.0055
        beta: 
            distribution: positiveNormal
            params:
                mu: 106
                sigma: 260
        N:
            distribution: lognormalInteger
            params:
                mu: 6
                sigma: 1
        seasonality:
            params:
                amplitude: 0
                phase: 0
                period: 1

branchingModel: 
    type: perInfection
    params:
        branchingBeta:
            distribution: fixed
            value: 0.05

importationModel: 
    type: denovoPerTimestep
    params:
        newClusterBeta:
            distribution: fixed
            value: 0
        N:
            distribution: fixed
            value: 424000
        infections: 
            distribution: fixed
            value: 1

        
initialConditions:
    type: fixed
    clusters:
        distribution: fixed
        value: 1
        params: 
            N:
                distribution: fixed
                value: 424000
            latents:
                distribution: fixed
                value: 1
            
        